mysql:
  dataBase: autosign
  userName: root
  passWord: 123456
  port: 8086
  driverName: mysql
  host: url
  log-level: debug
  max-idle-conns: 10
  max-open-conns: 100
  conn-max-life-time: 5
#  ğŸ› ï¸ğŸ”§â›ï¸ğŸ—ï¸âš™ï¸ğŸ§¬ğŸ’¡
logger:
  level: info
  prefix: '[ğŸ› ï¸]'
  director: log
  showLine: true
  logInConsole: true
mail:
  host: you-host
  port: you-port
  user: you-user
  password: you-password
  ssl: true
  local-home:         #å¯é€‰