mysql:
  dataBase: autosign
  userName: root
  passWord: 123456789
  port: 1111
  driverName: mysql
  host: localhost
  log-level: debug
  max-idle-conns: 10
  max-open-conns: 100
  conn-max-life-time: 5
#  ğŸ› ï¸ğŸ”§â›ï¸ğŸ—ï¸âš™ï¸ğŸ§¬ğŸ’¡
logger:
  level: info
  prefix: '[ğŸ› ï¸]'
  director: log
  showLine: true
  logInConsole: true


