mysql:
  dataBase: autosign
  userName: root
  passWord: 123456
  port: 8086
  driverName: mysql
  host: url
  log-level: debug
  max-idle-conns: 10
  max-open-conns: 100
  conn-max-life-time: 5
#  ğŸ› ï¸ğŸ”§â›ï¸ğŸ—ï¸âš™ï¸ğŸ§¬ğŸ’¡
logger:
  level: info
  prefix: '[ğŸ› ï¸]'
  director: log
  showLine: true
  logInConsole: true
mail:
  host: you-host
  port: you-port
  user: you-user
  password: you-password
  ssl: true
  local-home:         #å¯é€‰
ai:
  token: #ä½¿ç”¨è®¯é£æ˜Ÿç«å¤§æ¨¡å‹ç”ŸæˆæŠ¥å‘Š
account:
  gongxueyun: #å¯¹å·¥å­¦äº‘å•ç”¨æˆ·æ— æ•°æ®åº“æœåŠ¡æ–°å¼€è´¦å·å¯†ç ç™»å½•
    off: true                                     #off: true or false æ˜¯å¦å¼€å¯å•ç”¨æˆ·åŠ è½½ï¼Œå•ç”¨æˆ·åŠ è½½å¼€å¯æ—¶æ— æ³•ä½¿ç”¨mysqlæ•°æ®
    phone: "13888888888"                          #phone: æ‰‹æœºå·ç 
    password: "your_password"                     #password: å¯†ç 
    country: "China"                              #country: å›½å®¶
    province: "Beijing"                           #province: çœä»½
    city: "Beijing"                               #city: åŸå¸‚
    area: "Chaoyang"                              #area: åœ°åŒº
    latitude: "39.929986"                         #latitude: çº¬åº¦
    longitude: "116.465416"                       #longitude: ç»åº¦
    email: "example@example.com"                  #email: é‚®ç®±åœ°å€
    address: "No. 1, Chaoyang District, Beijing"  #address: è¯¦ç»†åœ°å€
    type: "home"                                  #type: ç±»å‹ï¼ˆä¾‹å¦‚ï¼šhomeã€workï¼‰
  cx:
    phone:
    password: